### ISSUE TITLE
Dumps core ((trayer:254): Gtk-WARNING **: 18:47:16.465: cannot open display: :99)

### ISSUE THREAD

**Issue by MildlyInterested** [ich777/docker-megasync#1]
Started through Portainer with the following docker compose
```
---
version: '3.3'
services:
    megasync:
        container_name: ich777-megasync
        ports:
            - '8080:8080'
        environment:
            - UMASK=XXX
            - DATA_PERM=XXX
            - UID=XXXX
            - GID=XXXX
        volumes:
            - 'FOLDERS'
            - 'FOLDERS'
        restart: unless-stopped
        image: ich777/megasync
```
procues the following logfile:
```
usermod: no changes,
---Setting umask to 777---,
---Checking for optional scripts---,
---No optional script found, continuing---,
---Checking configuration for noVNC---,
Nothing to do, noVNC resizing set to default,
Nothing to do, noVNC qaulity set to default,
Nothing to do, noVNC compression set to default,
---Starting...---,
---Preparing Server---,
---Checking for old logfiles---,
---Checking for old display lock files---,
---Starting Xvfb server---,
---Starting x11vnc server---,
---Starting noVNC server---,
WebSocket server settings:,
  - Listen on :8080,
  - Web server. Web root: /usr/share/novnc,
  - No SSL/TLS support (no cert file),
  - Backgrounding (daemon),
---Starting MEGASync,
,
(trayer:254): Gtk-WARNING **: 18:47:16.465: cannot open display: :99,
Error for "xrdb -query" command: "/bin/bash: line 1: xrdb: command not found\n",
qt.qpa.xcb: could not connect to display :99,
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.,
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.,
,
Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, xcb.,
,
/opt/scripts/start-server.sh: line 28:   255 Aborted                 (core dumped) megasync,
```
this keeps looping
